spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cookbot
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    default-schema: public

logging:
  level:
    org.liquibase: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE